language: android
jdk: oraclejdk8

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-25.0.2
    - build-tools-27.0.3
    # The SDK version used to compile your project
    - android-25
    - android-27
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image, if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-27

before_install:
  - yes | sdkmanager "platforms;android-25"
  - yes | sdkmanager "platforms;android-27"

script:
  - bash ./gradlew clean assemble

branches:
  only:
    - master